# -*- coding: utf-8 -*-
"""matriz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6F-CIcNJ5G6bGmnHhmj2ByPZptuRm88
"""

matriz = [
    [1, 2, 3],
    [2, 5, 5],
    [1, 2, 0]
]

def suma_matriz(matriz):
    suma = 0
    for fila in matriz:
        suma += sum(fila)
    return suma

resultado = suma_matriz(matriz)
print(f"La sumatoria de los elementos de la matriz es: {resultado}")